#### Data import

In [1]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame
BF_logs_raw = pd.read_csv("./data/logs_apache.txt", header = None, delimiter = " ",error_bad_lines=False)
BF_logs_raw.head(2)

,0,1,2,3,4,5,6,7,8
0,[07/Jul/2017:12:10:00,+0200],GET /history/apollo/apollo-13/apollo-13.html H...,200,24478,-,frank frank 189.188.154.208 0 Mozilla/5.0 (Win...,800,-
1,[07/Jul/2017:12:15:00,+0200],GET /images/faq.gif HTTP/1.0,200,3243,-,bob 123456789 189.183.172.77 1 Mozilla/5.0 (Li...,1431,-

#### Processing

In [2]:
BF_temp = BF_logs_raw[[0,1,2,3,4,6,7]]
# split timestamp
BF_temp['date'] = BF_temp[0].str.split(":").str.get(0)
BF_temp['date'] = BF_temp['date'].str.split("[").str.get(1)
BF_temp['hour'] = BF_temp[0].str.split(":").str.get(1)
BF_temp['minute'] = BF_temp[0].str.split(":").str.get(2)
BF_temp['seconds'] = BF_temp[0].str.split(":").str.get(3)
BF_temp['zone']= BF_temp[1].str.split("+").str.get(1)
BF_temp['zone']= BF_temp['zone'].str.split("]").str.get(0)
# split protocol
BF_temp['protocol'] = BF_temp[2].str.split(" ").str.get(0)
BF_temp['info'] = BF_temp[2].str.split(" ").str.get(1)
# split comments
BF_temp['username'] = BF_temp[6].str.split(" ").str.get(0)
BF_temp['password'] = BF_temp[6].str.split(" ").str.get(1)
BF_temp['ip_address'] = BF_temp[6].str.split(" ").str.get(2)
BF_temp['comment'] = BF_temp[6].str.split(" ").str.get(4)
BF_temp['label'] = BF_temp[6].str.split(" ").str.get(3)
# drop innecessary columns
BF_temp = BF_temp.drop([0, 1, 2, 6], axis=1)
# rename & replace
BF_temp.rename(columns={3:'status', 4:'respsize', 7:'timed'}, inplace=True)
bf_logs = BF_temp[['ip_address','date','hour','minute','seconds','zone','protocol','username','password','status','respsize','timed','label']]
bf_logs.to_csv('./data/test.csv')
bf_logs.head()

D:\Anaconda3\lib\site-packages\ipykernel\__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
D:\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,ip_address,date,hour,minute,seconds,zone,protocol,username,password,status,respsize,timed,label
0,189.188.154.208,07/Jul/2017,12,10,00,0200,GET,frank,frank,200,24478,800,0
1,189.183.172.77,07/Jul/2017,12,15,00,0200,GET,bob,123456789,200,3243,1431,1
2,128.55.162.143,07/Jul/2017,12,20,00,0200,GET,alice,alice,200,28222,802,0
3,128.147.11.33,07/Jul/2017,12,25,00,0200,GET,ted,ted,200,16281,803,0
4,128.168.150.134,07/Jul/2017,12,30,00,0200,GET,dimi,dimi,200,20261,804,0